---
title: "bioreg"
author: "Andrew Charles"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(shiny)
library(leaflet)
library(dplyr)
library(terra)
library(sf)
library(devtools)
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
data <- st_as_sf(bioreg)
idcol <- "BIOREGNO"
idata <- data[,idcol] %>% st_set_geometry(NULL)

choices = idata[,idcol]
input <- list()
input$selection <- "11.1"
idx <- which(idata[,idcol] == input$selection)
#idx <- which(idata[,idcol] == idata[,idcol][1])
print(idx)
layer <- data[idx,] %>% st_transform(4326)

m <- leaflet(layer)  %>% addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.5,
              highlightOptions = highlightOptions(color = "white", weight = 2,
                                                  bringToFront = TRUE)) %>% addTiles()

  observe({
    pal <- colorpal()

    leafletProxy("map", data = filteredData()) %>%
      clearShapes() %>%
      addCircles(radius = ~10^mag/10, weight = 1, color = "#777777",
        fillColor = ~pal(mag), fillOpacity = 0.7, popup = ~paste(mag)
      )
  })

    #print(idx)
m
```


