---
title: "bioregions_vic"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{bioregions_vic}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r setup, include=FALSE}
#library(etna)
library(shiny)
library(leaflet)
library(dplyr)
library(terra)
library(sf)
library(devtools)
library(DT)
library(here)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
df <- load(file=file.path(here::here('bioreg.app/data'),'bioreg.rda'))
bdata <- st_as_sf(bioreg)
B <- bioreg %>% st_as_sf() %>% dplyr::select(BIOREGION)
terra::plot(B)
```

```{r}
bioreg_table <- bioreg %>% st_set_geometry(NULL)
datatable(bioreg, caption = "Victorian Bioregions")

```

One of the bioregions is displayed on the map below:

```{r}
idcol <- "BIOREGNO"
idata <- bdata[,idcol] %>% st_set_geometry(NULL)
choices = idata[,idcol]
input <- list()
input$selection <- "11.1"
idx <- which(idata[,idcol] == input$selection)
layer <- bdata[idx,] %>% st_transform(4326)

m <- leaflet(layer)  %>% 
        addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
                    opacity = 1.0, fillOpacity = 0.5,
                    highlightOptions = highlightOptions(color = "white", weight = 2,
                    bringToFront = TRUE)) %>% 
        addTiles() 

m
```

